title: Deep Soft Procrustes
description: for Markerless Volumetric Sensor Alignment
show_downloads: true
theme: jekyll-theme-cayman

github:
    model_url: https://github.com/VCL3D/StructureNet/releases
    repository_url: https://github.com/VCL3D/StructureNet/
    is_project_page: true
    repository_name: DeepSoftProcrustes
    owner_url: https://zokin.github.io
    owner_name: Nikolaos Zioulis
